spring:
  application:
    name: valuationdiamond

  mail:
    host: smtp.gmail.com
    port: 587
    username: giakhoi060708@gmail.com
    password: pqho vqrn nhco pbiz

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jackson:
    date-format = yyyy-MM-dd'T'HH:mm:ss.SSSXXX


  datasource:
    url: jdbc:mysql://viaduct.proxy.rlwy.net:13265/diamond_valuation_db?useSSL=false&serverTimezone=UTC
    username: root
    password: eScJWhrtZQvmdjnsjTnSsFiWXqEwXjFY
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        use_sql_comments: true

server:
    port: 8080


frontend:
  url: http://localhost:5173/



  #
  ##              google:
  ##                authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
  ##                token-uri: https://oauth2.googleapis.com/token
  ##                user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  ##                user-name-attribute: sub