spring:
  application:
    name: valuationdiamond

  mail:
    host: smtp.gmail.com
    port: 587
    username: giakhoi060708@gmail.com
    password: pqho vqrn nhco pbiz

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:mysql://viaduct.proxy.rlwy.net:13265/diamond_valuation_db?useSSL=true
    username: root
    password: eScJWhrtZQvmdjnsjTnSsFiWXqEwXjFY
    driver-class-name: com.mysql.cj.jdbc.Driver

#    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=diamond_valuation_db
#    username: sa
#    password: Gi@khoi221203
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    defer-datasource-initialization: true
  jackson:
    date-format = yyyy-MM-dd'T'HH:mm:ss.SSSXXX
server:
    port: 8080
frontend:
  url: http://localhost:5173/



  #
  ##              google:
  ##                authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
  ##                token-uri: https://oauth2.googleapis.com/token
  ##                user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  ##                user-name-attribute: sub